import type { Category, Lesson } from './types'

export const categories: Category[] = [
  { id: 'foundations', title: 'Foundations' },
  { id: 'classical-ai', title: 'Classical AI' },
  { id: 'machine-learning', title: 'Machine Learning' },
  { id: 'neural-networks', title: 'Neural Networks' },
  { id: 'computer-vision', title: 'Computer Vision' },
  { id: 'sequence-models', title: 'Sequence Models' },
  { id: 'transformers', title: 'Transformers' },
  { id: 'generative-ai', title: 'Generative AI' },
  { id: 'reinforcement-learning', title: 'Reinforcement Learning' },
  { id: 'modern-ai', title: 'Modern AI' },
]

export const lessons: Lesson[] = [
  {
    id: 'vectors',
    number: 1,
    title: 'Vectors',
    description: 'A vector represents magnitude and direction.',
    category: 'foundations',
    difficulty: 'beginner',
    prerequisites: [],
    status: 'available',
  },
  {
    id: 'matrices',
    number: 2,
    title: 'Matrices',
    description: 'Matrices organize transformations and relationships.',
    category: 'foundations',
    difficulty: 'beginner',
    prerequisites: ['vectors'],
    status: 'planned',
  },
  {
    id: 'derivatives',
    number: 3,
    title: 'Derivatives',
    description: 'Derivatives describe how values change.',
    category: 'foundations',
    difficulty: 'beginner',
    prerequisites: [],
    status: 'planned',
  },
  {
    id: 'gradients',
    number: 4,
    title: 'Gradients',
    description: 'Gradients point toward the steepest change.',
    category: 'foundations',
    difficulty: 'beginner',
    prerequisites: ['derivatives'],
    status: 'planned',
  },
  {
    id: 'search',
    number: 5,
    title: 'Search',
    description: 'Search explores possible paths to a goal.',
    category: 'classical-ai',
    difficulty: 'beginner',
    prerequisites: [],
    status: 'planned',
  },
  {
    id: 'a-star',
    number: 6,
    title: 'A*',
    description: 'A* guides search with an informed estimate.',
    category: 'classical-ai',
    difficulty: 'intermediate',
    prerequisites: ['search'],
    status: 'planned',
  },
  {
    id: 'minimax',
    number: 7,
    title: 'Minimax',
    description: 'Minimax reasons about opposing decisions.',
    category: 'classical-ai',
    difficulty: 'intermediate',
    prerequisites: ['search'],
    status: 'planned',
  },
  {
    id: 'regression',
    number: 8,
    title: 'Regression',
    description: 'Regression learns a relationship between variables.',
    category: 'machine-learning',
    difficulty: 'beginner',
    prerequisites: ['vectors'],
    status: 'planned',
  },
  {
    id: 'knn',
    number: 9,
    title: 'K-nearest neighbors',
    description: 'KNN predicts from nearby examples.',
    category: 'machine-learning',
    difficulty: 'beginner',
    prerequisites: ['vectors'],
    status: 'planned',
  },
  {
    id: 'clustering',
    number: 10,
    title: 'Clustering',
    description: 'Clustering discovers groups without labels.',
    category: 'machine-learning',
    difficulty: 'intermediate',
    prerequisites: ['vectors'],
    status: 'planned',
  },
  {
    id: 'perceptron',
    number: 11,
    title: 'Perceptron',
    description: 'A perceptron is a small learnable decision unit.',
    category: 'neural-networks',
    difficulty: 'beginner',
    prerequisites: ['vectors'],
    status: 'planned',
  },
  {
    id: 'forward-propagation',
    number: 12,
    title: 'Forward propagation',
    description: 'Signals flow through a network to produce an output.',
    category: 'neural-networks',
    difficulty: 'intermediate',
    prerequisites: ['perceptron'],
    status: 'planned',
  },
  {
    id: 'backpropagation',
    number: 13,
    title: 'Backpropagation',
    description: 'Error signals travel backward to update a network.',
    category: 'neural-networks',
    difficulty: 'advanced',
    prerequisites: ['gradients', 'forward-propagation'],
    status: 'planned',
  },
  {
    id: 'convolution',
    number: 14,
    title: 'Convolution',
    description: 'Convolutions find local patterns in spatial data.',
    category: 'computer-vision',
    difficulty: 'intermediate',
    prerequisites: ['matrices'],
    status: 'planned',
  },
]

export const getLesson = (id: string) =>
  lessons.find((lesson) => lesson.id === id)
export const getCategory = (id: string) =>
  categories.find((category) => category.id === id)
export const lessonsByCategory = (id: string) =>
  lessons.filter((lesson) => lesson.category === id)
